version: '3.8'
services:
  samba:
    container_name: samba
    restart: always
    build: .
    network_mode: "host"
    expose:  
      - 445
    volumes:
      - ./share:/media/NAS
      - ./smb.conf:/etc/samba/smb.conf
